/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    targets: Target;
    exercises: Exercise;
    programs: Program;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    targets: {
      relatedExercises: 'exercises';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    targets: TargetsSelect<false> | TargetsSelect<true>;
    exercises: ExercisesSelect<false> | ExercisesSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'feature-flags': FeatureFlag;
  };
  globalsSelect: {
    'feature-flags': FeatureFlagsSelect<false> | FeatureFlagsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "targets".
 */
export interface Target {
  id: number;
  name: string;
  /**
   * URL-safe identifier. Auto-filled from Name, editable.
   */
  slug: string;
  targetType: 'body_part' | 'muscle_region' | 'core' | 'warm_up' | 'cool_down' | 'mobility' | 'conditioning' | 'other';
  /**
   * e.g. "Upper Chest" → "Chest", "Rear Shoulders" → "Shoulders"
   */
  parentTarget?: (number | null) | Target;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  /**
   * Inactive targets stay attached to existing content but are hidden from new selections.
   */
  active?: boolean | null;
  displayOrder?: number | null;
  relatedExercises?: {
    docs?: (number | Exercise)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises".
 */
export interface Exercise {
  id: number;
  name: string;
  /**
   * URL-safe identifier. Auto-filled from Name, editable.
   */
  slug: string;
  targets: (number | Target)[];
  primaryTarget?: (number | null) | Target;
  category: 'strength' | 'core' | 'warm_up' | 'cool_down' | 'mobility' | 'cardio' | 'recovery' | 'other';
  equipment?:
    | (
        | 'barbell'
        | 'dumbbell'
        | 'cable'
        | 'machine'
        | 'bench'
        | 'bodyweight'
        | 'resistance_band'
        | 'treadmill'
        | 'stationary_bike'
        | 'other'
      )[]
    | null;
  /**
   * How sets are measured by default. Individual program items can override this.
   */
  defaultMeasurementType: 'total_weight' | 'weight_each' | 'bodyweight' | 'duration';
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coachingNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * General alternatives. Individual program items may override these.
   */
  defaultAlternatives?: (number | Exercise)[] | null;
  image?: (number | null) | Media;
  demoVideo?: (number | null) | Media;
  /**
   * Inactive exercises stay visible in programs already using them but are hidden from new selections.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  name: string;
  subtitle?: string | null;
  /**
   * URL-safe identifier. Auto-filled from Name, editable while in draft — locked once first published.
   */
  slug: string;
  /**
   * Short label for tiles and the logger, e.g. "Bro", "PPLUL".
   */
  abbreviation: string;
  shortDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  weeks: number;
  daysPerWeek: number;
  sessionMinutes?: number | null;
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'all_levels';
  programType: 'bro_split' | 'ppl' | 'upper_lower' | 'full_body' | 'strength' | 'mobility' | 'custom';
  customProgramTypeLabel?: string | null;
  coverImage?: (number | null) | Media;
  featured?: boolean | null;
  active?: boolean | null;
  sections?:
    | (
        | {
            title: string;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            items?:
              | {
                  itemType: 'exercise' | 'text';
                  exercise?: (number | null) | Exercise;
                  /**
                   * Free-text prescription summary, e.g. "10–15 reps" or "5 min easy".
                   */
                  prescriptionText?: string | null;
                  textContent?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  instructions?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            extraInfo?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            initiallyExpanded?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'warmUp';
          }
        | {
            /**
             * Stable identifier, e.g. "weeks-1-5". Locked once the program is first published — logged workouts reference it.
             */
            phaseKey: string;
            name: string;
            /**
             * e.g. "Weeks 1–5 — Foundation". Editable.
             */
            displayTitle?: string | null;
            phaseType:
              | 'introduction'
              | 'foundation'
              | 'progression'
              | 'strength'
              | 'hypertrophy'
              | 'conditioning'
              | 'recovery'
              | 'deload'
              | 'assessment'
              | 'custom';
            customTypeLabel?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Admin-only. Never exposed through the public API.
             */
            internalNotes?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            contentMode: 'create' | 'reuse' | 'info';
            startWeek?: number | null;
            endWeek?: number | null;
            /**
             * Must reference another phase in this program whose Content Mode is Create (no chaining reuse-of-reuse, which also rules out circular references).
             */
            sourcePhaseKey?: string | null;
            /**
             * Multiplier applied to the source phase's set counts (e.g. 0.5 for a deload). Prefill rounds up, minimum 1.
             */
            setsScale?: number | null;
            dayOverrides?:
              | {
                  dayNumber: number;
                  excluded?: boolean | null;
                  notes?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            days?:
              | {
                  dayNumber: number;
                  dayName: string;
                  /**
                   * Defaults to "Day {number} — {name}". Editable.
                   */
                  displayTitle?: string | null;
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  focusTargets?: (number | Target)[] | null;
                  warmUpBehavior: 'use_program' | 'add_to_program' | 'replace_program' | 'none';
                  dayWarmUpItems?:
                    | {
                        itemType: 'exercise' | 'text';
                        exercise?: (number | null) | Exercise;
                        /**
                         * Free-text prescription summary, e.g. "10–15 reps" or "5 min easy".
                         */
                        prescriptionText?: string | null;
                        textContent?: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        } | null;
                        instructions?: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        } | null;
                        id?: string | null;
                      }[]
                    | null;
                  exerciseGroups?:
                    | {
                        name: string;
                        workoutType?:
                          | (
                              | 'Full Body'
                              | 'Upper Body'
                              | 'Lower Body'
                              | 'Push'
                              | 'Pull'
                              | 'Legs'
                              | 'Chest'
                              | 'Back'
                              | 'Shoulders'
                              | 'Arms'
                              | 'Biceps'
                              | 'Triceps'
                              | 'Core / Abs'
                              | 'Calves'
                              | 'Forearms'
                              | 'Cardio'
                              | 'HIIT'
                              | 'Mobility / Recovery'
                              | 'Rest Day'
                              | 'Other'
                            )
                          | null;
                        groupTarget?: (number | null) | Target;
                        description?: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        } | null;
                        items?:
                          | {
                              exercise: number | Exercise;
                              /**
                               * Overrides the exercise's default measurement type for this item only.
                               */
                              measurementType?: ('total_weight' | 'weight_each' | 'bodyweight' | 'duration') | null;
                              sets?: number | null;
                              prescriptionType:
                                'fixed' | 'range' | 'time' | 'distance' | 'until_comfortable' | 'custom';
                              fixedReps?: number | null;
                              minReps?: number | null;
                              maxReps?: number | null;
                              durationValue?: number | null;
                              durationUnit?: ('sec' | 'min') | null;
                              distanceValue?: number | null;
                              distanceUnit?: ('m' | 'km' | 'mi') | null;
                              /**
                               * Use only when the prescription can't be represented by the structured fields above.
                               */
                              customPrescription?: {
                                root: {
                                  type: string;
                                  children: {
                                    type: any;
                                    version: number;
                                    [k: string]: unknown;
                                  }[];
                                  direction: ('ltr' | 'rtl') | null;
                                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                  indent: number;
                                  version: number;
                                };
                                [k: string]: unknown;
                              } | null;
                              perSide?: boolean | null;
                              perSideLabel?: ('side' | 'arm' | 'leg') | null;
                              minRestSec?: number | null;
                              maxRestSec?: number | null;
                              /**
                               * Pre-populate from the exercise's Default Alternatives, then adjust for this program item only.
                               */
                              alternatives?: (number | Exercise)[] | null;
                              notes?: {
                                root: {
                                  type: string;
                                  children: {
                                    type: any;
                                    version: number;
                                    [k: string]: unknown;
                                  }[];
                                  direction: ('ltr' | 'rtl') | null;
                                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                  indent: number;
                                  version: number;
                                };
                                [k: string]: unknown;
                              } | null;
                              extraInfo?: {
                                root: {
                                  type: string;
                                  children: {
                                    type: any;
                                    version: number;
                                    [k: string]: unknown;
                                  }[];
                                  direction: ('ltr' | 'rtl') | null;
                                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                  indent: number;
                                  version: number;
                                };
                                [k: string]: unknown;
                              } | null;
                              enabled?: boolean | null;
                              id?: string | null;
                            }[]
                          | null;
                        displayTableHeader?: boolean | null;
                        enabled?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * Structured interval rounds, e.g. for a HIIT day. Leave empty if this day has none.
                   */
                  intervals?: {
                    intro?: {
                      root: {
                        type: string;
                        children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    } | null;
                    rounds?:
                      | {
                          label: string;
                          warmUp?: string | null;
                          hardEffort: string;
                          recovery: string;
                          repeat: string;
                          note?: string | null;
                          id?: string | null;
                        }[]
                      | null;
                    coolDown?: string | null;
                  };
                  progressionNote?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  extraInfo?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  enabled?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            instructions?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            progressionGuidance?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            recoveryGuidance?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            initiallyExpanded?: boolean | null;
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'phase';
          }
        | {
            title: string;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            items?:
              | {
                  itemType: 'exercise' | 'text';
                  exercise?: (number | null) | Exercise;
                  /**
                   * Free-text prescription summary, e.g. "10–15 reps" or "5 min easy".
                   */
                  prescriptionText?: string | null;
                  textContent?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  instructions?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            extraInfo?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            initiallyExpanded?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'coolDown';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            displayStyle?: ('standard' | 'information' | 'success' | 'warning' | 'safety') | null;
            collapsible?: boolean | null;
            initiallyExpanded?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            title: string;
            safetyContent: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            requireAcknowledgement?: boolean | null;
            acknowledgementContent?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            actionLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'safety';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'targets';
        value: number | Target;
      } | null)
    | ({
        relationTo: 'exercises';
        value: number | Exercise;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "targets_select".
 */
export interface TargetsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  targetType?: T;
  parentTarget?: T;
  description?: T;
  image?: T;
  active?: T;
  displayOrder?: T;
  relatedExercises?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises_select".
 */
export interface ExercisesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  targets?: T;
  primaryTarget?: T;
  category?: T;
  equipment?: T;
  defaultMeasurementType?: T;
  instructions?: T;
  coachingNotes?: T;
  defaultAlternatives?: T;
  image?: T;
  demoVideo?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  name?: T;
  subtitle?: T;
  slug?: T;
  abbreviation?: T;
  shortDescription?: T;
  fullDescription?: T;
  weeks?: T;
  daysPerWeek?: T;
  sessionMinutes?: T;
  difficulty?: T;
  programType?: T;
  customProgramTypeLabel?: T;
  coverImage?: T;
  featured?: T;
  active?: T;
  sections?:
    | T
    | {
        warmUp?:
          | T
          | {
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    itemType?: T;
                    exercise?: T;
                    prescriptionText?: T;
                    textContent?: T;
                    instructions?: T;
                    id?: T;
                  };
              extraInfo?: T;
              initiallyExpanded?: T;
              id?: T;
              blockName?: T;
            };
        phase?:
          | T
          | {
              phaseKey?: T;
              name?: T;
              displayTitle?: T;
              phaseType?: T;
              customTypeLabel?: T;
              description?: T;
              internalNotes?: T;
              contentMode?: T;
              startWeek?: T;
              endWeek?: T;
              sourcePhaseKey?: T;
              setsScale?: T;
              dayOverrides?:
                | T
                | {
                    dayNumber?: T;
                    excluded?: T;
                    notes?: T;
                    id?: T;
                  };
              days?:
                | T
                | {
                    dayNumber?: T;
                    dayName?: T;
                    displayTitle?: T;
                    description?: T;
                    focusTargets?: T;
                    warmUpBehavior?: T;
                    dayWarmUpItems?:
                      | T
                      | {
                          itemType?: T;
                          exercise?: T;
                          prescriptionText?: T;
                          textContent?: T;
                          instructions?: T;
                          id?: T;
                        };
                    exerciseGroups?:
                      | T
                      | {
                          name?: T;
                          workoutType?: T;
                          groupTarget?: T;
                          description?: T;
                          items?:
                            | T
                            | {
                                exercise?: T;
                                measurementType?: T;
                                sets?: T;
                                prescriptionType?: T;
                                fixedReps?: T;
                                minReps?: T;
                                maxReps?: T;
                                durationValue?: T;
                                durationUnit?: T;
                                distanceValue?: T;
                                distanceUnit?: T;
                                customPrescription?: T;
                                perSide?: T;
                                perSideLabel?: T;
                                minRestSec?: T;
                                maxRestSec?: T;
                                alternatives?: T;
                                notes?: T;
                                extraInfo?: T;
                                enabled?: T;
                                id?: T;
                              };
                          displayTableHeader?: T;
                          enabled?: T;
                          id?: T;
                        };
                    intervals?:
                      | T
                      | {
                          intro?: T;
                          rounds?:
                            | T
                            | {
                                label?: T;
                                warmUp?: T;
                                hardEffort?: T;
                                recovery?: T;
                                repeat?: T;
                                note?: T;
                                id?: T;
                              };
                          coolDown?: T;
                        };
                    progressionNote?: T;
                    extraInfo?: T;
                    enabled?: T;
                    id?: T;
                  };
              instructions?: T;
              progressionGuidance?: T;
              recoveryGuidance?: T;
              initiallyExpanded?: T;
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        coolDown?:
          | T
          | {
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    itemType?: T;
                    exercise?: T;
                    prescriptionText?: T;
                    textContent?: T;
                    instructions?: T;
                    id?: T;
                  };
              extraInfo?: T;
              initiallyExpanded?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              title?: T;
              content?: T;
              displayStyle?: T;
              collapsible?: T;
              initiallyExpanded?: T;
              id?: T;
              blockName?: T;
            };
        safety?:
          | T
          | {
              title?: T;
              safetyContent?: T;
              requireAcknowledgement?: T;
              acknowledgementContent?: T;
              actionLabel?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Switch features Off, Coming soon or Live. Production and preview deployments share this CMS, so Live here means Live in production. Test unfinished work with the FEATURE_FLAGS_OVERRIDE environment variable instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags".
 */
export interface FeatureFlag {
  id: number;
  /**
   * Paid, personalised programs offered on the Programs page.
   */
  custom_programs: 'off' | 'coming_soon' | 'live';
  /**
   * Create or join a community, with posts, comments and reactions.
   */
  community: 'off' | 'coming_soon' | 'live';
  updatedBy?: (number | null) | User;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags_select".
 */
export interface FeatureFlagsSelect<T extends boolean = true> {
  custom_programs?: T;
  community?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}